version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/iluovo-app/
hooks:
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: root